
# Spring properties
spring:
  profiles:
    active: development2
  main:
    web-environment: false
  application:
    name: attachments-auto-upload

app:
  name: attachments-auto-upload
