
app:
  name: invoice-uploader

# Google configuration
google:
  app.name: invoice-uploader
  client:
    id: <id>
    secret: <secret>

# Email configuration
email:
  host: imap.gmail.com
  username: something@gmail.com
  password: password
  monitor:
    folder: "[Gmail]/All Mail"
    days.older: 50
  attachments.temporary.folder: ./temp

# Email filter
filter:
  types:
    - type: communications
      from: (.*)@vodafone.pt
      subject: (.*)fatura(.*)
      attachments: (.*).pdf
      fileName: ${receivedDate}_${originalName}.${extension}
      fileMimeType: application/pdf
      folder: communications
      folderId: 111111111
    - type: electricity
      from: (.*)@edp.pt
      subject: (.*)fatura(.*)
      attachments: (.*).pdf
      fileName: ${receivedDate}_${originalName}.${extension}
      fileMimeType: application/pdf
      folder: electricity
      folderId: 111111112
    - type: gas
      from: (.*)@galpenergia.com
      subject: (.*)Envio de Fatura(.*)
      attachments: (.*).pdf
      fileName: ${receivedDate}_${originalName}.${extension}
      fileMimeType: application/pdf
      folder: Gas
      folderId: 111111113
    - type: rent
      from: (.*)@activobank.pt
      subject: (.*)Documentos em formato digital(.*)
      attachments: NL_(.*).pdf
      fileName: ${receivedDate}_${originalName}.${extension}
      fileMimeType: application/pdf
      folder: Rent
      folderId: 111111114