
# Google configuration
google:
  app.name: ${app.name}
  client:
    id: <id>
    secret: <secret>

# Email configuration
email:
  host: imap.gmail.com
  username: something@gmail.com
  password: password
  monitor:
    folder: "[Gmail]/All Mail"
    days.older: 50
    subject.pattern: (.*)(fatura|Fatura)(.*)
  attachments.temporary.folder: ./temp

# Email filter
filter:
  types:
    - type: 3play
      from: (.*)@vodafone.pt
      subject: (.*)fatura(.*)
      attachments: (.*).pdf
      fileName: ${receivedDate}_${originalName}.${extension}
      fileMimeType: application/pdf
      merge: true
      mergeOrder: ASC
      folder: communications
      folderId: 111111111
    - type: electricity
      from: (.*)@edp.pt
      subject: (.*)fatura(.*)
      attachments: (.*).pdf
      fileName: ${receivedDate}_${originalName}.${extension}
      fileMimeType: application/pdf
      folder: electricity
      folderId: 111111112
    - type: gas
      from: (.*)@galpenergia.com
      subject: (.*)Envio de Fatura(.*)
      attachments: (.*).pdf
      fileName: ${receivedDate}_${originalName}.${extension}
      fileMimeType: application/pdf
      folder: Gas
      folderId: 111111113