
# Google configuration
google:
  app.name: ${app.name}
  client:
    id: <id>
    secret: <secret>

# Email configuration
email:
  host: imap.gmail.com
  username: something@gmail.com
  password: password
  monitor:
    folder: "[Gmail]/All Mail"
    days.older: 50
    subject.pattern: (.*)(fatura|Fatura)(.*)
  attachments.temporary.folder: ./temp

# Email filter
filter:
  default:
    fileName: "%{receivedDate}_%{originalName}.%{extension}"
    fileType: application/pdf
    attachments: (.*).pdf
  types:
    - type: 3play
      from: (.*)@vodafone.pt
      subject: (.*)fatura(.*)
      mergeOrder: ASC
      folder: communications
      folderId: 111111111
      attachments: ${filter.default.attachments}
      fileName: ${filter.default.fileName}
      fileMimeType: ${filter.default.fileType}
    - type: electricity
      from: (.*)@edp.pt
      subject: (.*)fatura(.*)
      folder: electricity
      folderId: 111111112
      attachments: ${filter.default.attachments}
      fileName: ${filter.default.fileName}
      fileMimeType: ${filter.default.fileType}
    - type: gas
      from: (.*)@galpenergia.com
      subject: (.*)Envio de Fatura(.*)
      folder: Gas
      folderId: 111111113
      attachments: ${filter.default.attachments}
      fileName: ${filter.default.fileName}
      fileMimeType: ${filter.default.fileType}